# Generated by Django 4.2 on 2025-10-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='items/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='url shop-category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
    ]
