# Generated by Django 5.2.5 on 2025-08-13 12:20

import media_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создано_at'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='desc',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=media_app.models.image_upload_to, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=media_app.models.video_upload_to, verbose_name='видео'),
        ),
    ]
