# Generated by Django 4.2 on 2025-10-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifikat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификат'},
        ),
    ]
